repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    # https://github.com/pre-commit/pre-commit-hooks
    hooks:
      # ファイルが有効な Python として解析されるかどうかを単純にチェックします。
      - id: check-ast

      # 大文字と小文字を区別しないファイルシステムで競合する可能性のあるファイルをチェックします。
      - id: check-case-conflict

      # 非バイナリ実行可能ファイルにシバンがあることを確認します。
      - id: check-executables-have-shebangs

      # ファイルが有効な JSON として解析されるかどうかを単純にチェックします。
      - id: check-json
        exclude: ^tsconfig\.json$

      # シバンを持つ (非バイナリ) ファイルが実行可能であることを確認します。
      - id: check-shebang-scripts-are-executable

      # マージコンフリクトの残骸をチェックします。
      - id: check-merge-conflict

      # ファイルが有効な YAML として解析されるかどうかを単純にチェックします。
      - id: check-yaml

      # AWS CLI で設定した AWS シークレットの存在を確認します。
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]

      # プライベートキーの存在を確認します。
      - id: detect-private-key

      # ファイルが改行で終わり、改行のみであることを確認します。
      - id: end-of-file-fixer

      # 混合行末を置換またはチェックします。
      - id: mixed-line-ending
        args: [--fix=no]

      # テストファイルの名前がテストを含んでいることを確認します。
      - id: name-tests-test
        args: [--django]

      # ブランチ名が指定されたパターンに一致するときにコミットを拒否します。
      - id: no-commit-to-branch
        args: [--branch, main, --branch, develop]

      # 末尾の空白をトリムします。
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.11
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: ^(pnpm-lock\.yaml|Pipfile\.lock)$
        args:
          ["--check-filenames", "--ignore-words-list", "https://neightbor.jp"]

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
        files: (\.json5|tsconfig.json)$
